metrics:
  endpoint: http://localhost:9000
  tolerance: 10
spring:
  application:
    name: test-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: p@ssword
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
      ddl-auto: update
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
  jackson:
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      group-id: test-manager
    template:
      default-topic: my-topic

springdoc:
  api-docs:
    path: /open-api
  swagger-ui:
    path: /